export const cities = [
  // São Paulo (SP)
  { name: 'São Paulo', uf: 'SP', slug: 'sao-paulo', region: 'Sudeste' },
  { name: 'Guarulhos', uf: 'SP', slug: 'guarulhos', region: 'Sudeste' },
  { name: 'Campinas', uf: 'SP', slug: 'campinas', region: 'Sudeste' },
  { name: 'São Bernardo do Campo', uf: 'SP', slug: 'sao-bernardo-do-campo', region: 'Sudeste' },
  { name: 'Santo André', uf: 'SP', slug: 'santo-andre', region: 'Sudeste' },
  { name: 'Osasco', uf: 'SP', slug: 'osasco', region: 'Sudeste' },
  { name: 'São José dos Campos', uf: 'SP', slug: 'sao-jose-dos-campos', region: 'Sudeste' },
  { name: 'Ribeirão Preto', uf: 'SP', slug: 'ribeirao-preto', region: 'Sudeste' },
  { name: 'Sorocaba', uf: 'SP', slug: 'sorocaba', region: 'Sudeste' },
  { name: 'Mauá', uf: 'SP', slug: 'maua', region: 'Sudeste' },
  { name: 'Santos', uf: 'SP', slug: 'santos', region: 'Sudeste' },
  { name: 'Diadema', uf: 'SP', slug: 'diadema', region: 'Sudeste' },
  { name: 'Jundiaí', uf: 'SP', slug: 'jundiai', region: 'Sudeste' },
  { name: 'Mogi das Cruzes', uf: 'SP', slug: 'mogi-das-cruzes', region: 'Sudeste' },
  { name: 'Piracicaba', uf: 'SP', slug: 'piracicaba', region: 'Sudeste' },
  { name: 'Carapicuíba', uf: 'SP', slug: 'carapicuiba', region: 'Sudeste' },
  { name: 'Bauru', uf: 'SP', slug: 'bauru', region: 'Sudeste' },
  { name: 'Itaquaquecetuba', uf: 'SP', slug: 'itaquaquecetuba', region: 'Sudeste' },
  { name: 'São Vicente', uf: 'SP', slug: 'sao-vicente', region: 'Sudeste' },
  { name: 'Franca', uf: 'SP', slug: 'franca', region: 'Sudeste' },
  { name: 'Taubaté', uf: 'SP', slug: 'taubate', region: 'Sudeste' },
  { name: 'Limeira', uf: 'SP', slug: 'limeira', region: 'Sudeste' },
  { name: 'Suzano', uf: 'SP', slug: 'suzano', region: 'Sudeste' },
  { name: 'São Carlos', uf: 'SP', slug: 'sao-carlos', region: 'Sudeste' },
  { name: 'Indaiatuba', uf: 'SP', slug: 'indaiatuba', region: 'Sudeste' },
  { name: 'Cotia', uf: 'SP', slug: 'cotia', region: 'Sudeste' },
  { name: 'Americana', uf: 'SP', slug: 'americana', region: 'Sudeste' },
  { name: 'Barueri', uf: 'SP', slug: 'barueri', region: 'Sudeste' },
  { name: 'Marília', uf: 'SP', slug: 'marilia', region: 'Sudeste' },
  { name: 'Presidente Prudente', uf: 'SP', slug: 'presidente-prudente', region: 'Sudeste' },
  { name: 'Araçatuba', uf: 'SP', slug: 'aracatuba', region: 'Sudeste' },
  { name: 'Araraquara', uf: 'SP', slug: 'araraquara', region: 'Sudeste' },

  // Minas Gerais (MG)
  { name: 'Belo Horizonte', uf: 'MG', slug: 'belo-horizonte', region: 'Sudeste' },
  { name: 'Uberlândia', uf: 'MG', slug: 'uberlandia', region: 'Sudeste' },
  { name: 'Contagem', uf: 'MG', slug: 'contagem', region: 'Sudeste' },
  { name: 'Juiz de Fora', uf: 'MG', slug: 'juiz-de-fora', region: 'Sudeste' },
  { name: 'Betim', uf: 'MG', slug: 'betim', region: 'Sudeste' },
  { name: 'Montes Claros', uf: 'MG', slug: 'montes-claros', region: 'Sudeste' },
  { name: 'Uberaba', uf: 'MG', slug: 'uberaba', region: 'Sudeste' },
  { name: 'Governador Valadares', uf: 'MG', slug: 'governador-valadares', region: 'Sudeste' },
  { name: 'Ipatinga', uf: 'MG', slug: 'ipatinga', region: 'Sudeste' },
  { name: 'Sete Lagoas', uf: 'MG', slug: 'sete-lagoas', region: 'Sudeste' },
  { name: 'Divinópolis', uf: 'MG', slug: 'divinopolis', region: 'Sudeste' },
  { name: 'Ribeirão das Neves', uf: 'MG', slug: 'ribeirao-das-neves', region: 'Sudeste' },
  { name: 'Santa Luzia', uf: 'MG', slug: 'santa-luzia', region: 'Sudeste' },
  { name: 'Pouso Alegre', uf: 'MG', slug: 'pouso-alegre', region: 'Sudeste' },
  { name: 'Poços de Caldas', uf: 'MG', slug: 'pocos-de-caldas', region: 'Sudeste' },

  // Rio de Janeiro (RJ)
  { name: 'Rio de Janeiro', uf: 'RJ', slug: 'rio-de-janeiro', region: 'Sudeste' },
  { name: 'São Gonçalo', uf: 'RJ', slug: 'sao-goncalo', region: 'Sudeste' },
  { name: 'Duque de Caxias', uf: 'RJ', slug: 'duque-de-caxias', region: 'Sudeste' },
  { name: 'Nova Iguaçu', uf: 'RJ', slug: 'nova-iguacu', region: 'Sudeste' },
  { name: 'Niterói', uf: 'RJ', slug: 'niteroi', region: 'Sudeste' },
  { name: 'Belford Roxo', uf: 'RJ', slug: 'belford-roxo', region: 'Sudeste' },
  { name: 'Campos dos Goytacazes', uf: 'RJ', slug: 'campos-dos-goytacazes', region: 'Sudeste' },
  { name: 'São João de Meriti', uf: 'RJ', slug: 'sao-joao-de-meriti', region: 'Sudeste' },
  { name: 'Petrópolis', uf: 'RJ', slug: 'petropolis', region: 'Sudeste' },
  { name: 'Volta Redonda', uf: 'RJ', slug: 'volta-redonda', region: 'Sudeste' },
  { name: 'Macaé', uf: 'RJ', slug: 'macae', region: 'Sudeste' },
  { name: 'Cabo Frio', uf: 'RJ', slug: 'cabo-frio', region: 'Sudeste' },

  // Paraná (PR)
  { name: 'Curitiba', uf: 'PR', slug: 'curitiba', region: 'Sul' },
  { name: 'Londrina', uf: 'PR', slug: 'londrina', region: 'Sul' },
  { name: 'Maringá', uf: 'PR', slug: 'maringa', region: 'Sul' },
  { name: 'Ponta Grossa', uf: 'PR', slug: 'ponta-grossa', region: 'Sul' },
  { name: 'Cascavel', uf: 'PR', slug: 'cascavel', region: 'Sul' },
  { name: 'São José dos Pinhais', uf: 'PR', slug: 'sao-jose-dos-pinhais', region: 'Sul' },
  { name: 'Foz do Iguaçu', uf: 'PR', slug: 'foz-do-iguacu', region: 'Sul' },

  // Rio Grande do Sul (RS)
  { name: 'Porto Alegre', uf: 'RS', slug: 'porto-alegre', region: 'Sul' },
  { name: 'Caxias do Sul', uf: 'RS', slug: 'caxias-do-sul', region: 'Sul' },
  { name: 'Canoas', uf: 'RS', slug: 'canoas', region: 'Sul' },
  { name: 'Pelotas', uf: 'RS', slug: 'pelotas', region: 'Sul' },
  { name: 'Santa Maria', uf: 'RS', slug: 'santa-maria', region: 'Sul' },
  { name: 'Gravataí', uf: 'RS', slug: 'gravatai', region: 'Sul' },

  // Santa Catarina (SC)
  { name: 'Joinville', uf: 'SC', slug: 'joinville', region: 'Sul' },
  { name: 'Florianópolis', uf: 'SC', slug: 'florianopolis', region: 'Sul' },
  { name: 'Blumenau', uf: 'SC', slug: 'blumenau', region: 'Sul' },
  { name: 'São José', uf: 'SC', slug: 'sao-jose', region: 'Sul' },
  { name: 'Chapecó', uf: 'SC', slug: 'chapeco', region: 'Sul' },
  { name: 'Itajaí', uf: 'SC', slug: 'itajai', region: 'Sul' },

  // Espírito Santo (ES)
  { name: 'Serra', uf: 'ES', slug: 'serra', region: 'Sudeste' },
  { name: 'Vila Velha', uf: 'ES', slug: 'vila-velha', region: 'Sudeste' },
  { name: 'Cariacica', uf: 'ES', slug: 'cariacica', region: 'Sudeste' },
  { name: 'Vitória', uf: 'ES', slug: 'vitoria', region: 'Sudeste' },

  // Distrito Federal (DF)
  { name: 'Brasília', uf: 'DF', slug: 'brasilia', region: 'Centro-Oeste' },

  // Centro-Oeste
  { name: 'Goiânia', uf: 'GO', slug: 'goiania', region: 'Centro-Oeste' },
  { name: 'Aparecida de Goiânia', uf: 'GO', slug: 'aparecida-de-goiania', region: 'Centro-Oeste' },
  { name: 'Anápolis', uf: 'GO', slug: 'anapolis', region: 'Centro-Oeste' },
  { name: 'Campo Grande', uf: 'MS', slug: 'campo-grande', region: 'Centro-Oeste' },
  { name: 'Cuiabá', uf: 'MT', slug: 'cuiaba', region: 'Centro-Oeste' },

  // Nordeste
  { name: 'Salvador', uf: 'BA', slug: 'salvador', region: 'Nordeste' },
  { name: 'Feira de Santana', uf: 'BA', slug: 'feira-de-sentana', region: 'Nordeste' },
  { name: 'Vitória da Conquista', uf: 'BA', slug: 'vitoria-da-conquista', region: 'Nordeste' },
  { name: 'Fortaleza', uf: 'CE', slug: 'fortaleza', region: 'Nordeste' },
  { name: 'Recife', uf: 'PE', slug: 'recife', region: 'Nordeste' },
  { name: 'Jaboatão dos Guararapes', uf: 'PE', slug: 'jaboatao-dos-guararapes', region: 'Nordeste' },
  { name: 'Olinda', uf: 'PE', slug: 'olinda', region: 'Nordeste' },
  { name: 'Caruaru', uf: 'PE', slug: 'caruaru', region: 'Nordeste' },
  { name: 'Natal', uf: 'RN', slug: 'natal', region: 'Nordeste' },
  { name: 'João Pessoa', uf: 'PB', slug: 'joao-pessoa', region: 'Nordeste' },
  { name: 'Maceió', uf: 'AL', slug: 'maceio', region: 'Nordeste' },
  { name: 'Aracaju', uf: 'SE', slug: 'aracaju', region: 'Nordeste' },
  { name: 'Teresina', uf: 'PI', slug: 'teresina', region: 'Nordeste' },
  { name: 'São Luís', uf: 'MA', slug: 'sao-luis', region: 'Nordeste' },

  // Norte
  { name: 'Manaus', uf: 'AM', slug: 'manaus', region: 'Norte' },
  { name: 'Belém', uf: 'PA', slug: 'belem', region: 'Norte' },
  { name: 'Ananindeua', uf: 'PA', slug: 'ananindeua', region: 'Norte' },
  { name: 'Porto Velho', uf: 'RO', slug: 'porto-velho', region: 'Norte' },
  { name: 'Macapá', uf: 'AP', slug: 'macapa', region: 'Norte' },
  { name: 'Rio Branco', uf: 'AC', slug: 'rio-branco', region: 'Norte' },
  { name: 'Boa Vista', uf: 'RR', slug: 'boa-vista', region: 'Norte' },
  { name: 'Palmas', uf: 'TO', slug: 'palmas', region: 'Norte' }
];
