export const perfumes = [
  {
    code: "A001",
    name: "Perfume Lattafa Asad 25ml - Mini Perfume Masculino",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.9,
    gender: "Masculino",
    image: "/perfumes/A001 – Asad.webp",
    description: "Uma fragrância oriental e amadeirada, com notas ricas de especiarias quentes, baunilha suave e âmbar refinado. Ideal para homens imponentes e misteriosos.",
    notes: ["Pimenta Preta", "Abacaxi", "Tabaco", "Café", "Patchouli", "Âmbar", "Baunilha"],
    stock: 12,
    googleCategory: "Vestuário e acessórios > Joias e relógios > Relógios",
    slug: "lattafa-asad-25ml",
    categorySlugs: ["mini-perfumes-importados", "mini-perfumes-25ml", "mini-perfumes-masculinos", "arabic-collection", "mini-perfumes-para-presente", "mini-perfumes-em-bh"]
  },
  {
    code: "A002",
    name: "Perfume Lattafa Yara 25ml - Mini Perfume Feminino",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.9,
    gender: "Feminino",
    image: "/perfumes/A002- Yara.webp",
    description: "Um aroma doce, gourmand e extremamente envolvente. Com notas cremosas de baunilha, tangerina fresca e acordes tropicais de heliotrópio.",
    notes: ["Heliotrópio", "Tangerina", "Orquídea", "Notas Tropicais", "Baunilha", "Almíscar", "Sândalo"],
    stock: 8,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia",
    slug: "lattafa-yara-25ml",
    categorySlugs: ["mini-perfumes-importados", "mini-perfumes-25ml", "mini-perfumes-femininos", "arabic-collection", "mini-perfumes-para-presente", "mini-perfumes-em-bh"]
  },
  {
    code: "A003",
    name: "Perfume Lattafa Yara Tous Laranja 25ml - Mini Perfume Feminino",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.9,
    gender: "Feminino",
    image: "/perfumes/A003- Yara Tous Laranja.webp",
    description: "Explosão frutada e tropical irresistível. Traz uma combinação solar de manga suculenta, maracujá doce e leite de coco cremoso.",
    notes: ["Manga", "Maracujá", "Coco", "Heliotrópio", "Jasmim", "Flor de Laranjeira", "Baunilha", "Almíscar"],
    stock: 15,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia",
    slug: "lattafa-yara-tous-laranja-25ml",
    categorySlugs: ["mini-perfumes-importados", "mini-perfumes-25ml", "mini-perfumes-femininos", "arabic-collection", "mini-perfumes-para-presente", "mini-perfumes-em-bh"]
  },
  {
    code: "A004",
    name: "Perfume Lattafa Yara Moi Branco 25ml - Mini Perfume Feminino",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.9,
    gender: "Feminino",
    image: "/perfumes/A004- Yara Moi Branco.webp",
    description: "Fragrância exótica que une a doçura do pêssego caramelizado à sofisticação do jasmim e do patchouli terroso.",
    notes: ["Pêssego", "Jasmim", "Caramelo", "Âmbar", "Patchouli", "Sândalo"],
    stock: 9,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia",
    slug: "lattafa-yara-moi-branco-25ml",
    categorySlugs: ["mini-perfumes-importados", "mini-perfumes-25ml", "mini-perfumes-femininos", "arabic-collection", "mini-perfumes-para-presente", "mini-perfumes-em-bh"]
  },
  {
    code: "A005",
    name: "Perfume Lattafa Khamrah 25ml - Mini Perfume Compartilhável",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.9,
    gender: "Compartilhável",
    image: "/perfumes/A005- Khamrah.webp",
    description: "Aroma luxuoso e quente com acordes licorosos de conhaque, tâmaras doces, canela e pralina cremosa. Altamente sofisticado.",
    notes: ["Canela", "Noz-moscada", "Tâmaras", "Pralina", "Tuberosa", "Baunilha", "Âmbar", "Mirra"],
    stock: 14,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia",
    slug: "lattafa-khamrah-25ml",
    categorySlugs: ["mini-perfumes-importados", "mini-perfumes-25ml", "mini-perfumes-unissex", "arabic-collection", "mini-perfumes-para-presente", "mini-perfumes-em-bh"]
  },
  {
    code: "A006",
    name: "Perfume Lattafa Fakhar Rose 25ml - Mini Perfume Feminino",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.9,
    gender: "Feminino",
    image: "/perfumes/A006- Fakhar Rose.webp",
    description: "Um buquê floral branco elegante e fresco. Combina jasmim e lírio a um toque de mel e almíscar suave.",
    notes: ["Lírio", "Romã", "Jasmim", "Flor de Laranjeira", "Rosa", "Mel", "Almíscar", "Sândalo"],
    stock: 7,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia",
    slug: "lattafa-fakhar-rose-25ml",
    categorySlugs: ["mini-perfumes-importados", "mini-perfumes-25ml", "mini-perfumes-femininos", "arabic-collection", "mini-perfumes-para-presente", "mini-perfumes-em-bh"]
  },
  {
    code: "A007",
    name: "Perfume Lattafa Fakhar Black 25ml - Mini Perfume Masculino",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.9,
    gender: "Masculino",
    image: "/perfumes/A007 - Fakhar Black.webp",
    description: "Fragrância fougère moderna com maçã crocante, lavanda aromática e notas amadeiradas profundas de cedro e âmbar.",
    notes: ["Maçã", "Gengibre", "Lavanda", "Sálvia", "Junípero", "Tonka", "Âmbar", "Cedro"],
    stock: 11,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia",
    slug: "lattafa-fakhar-black-25ml",
    categorySlugs: ["mini-perfumes-importados", "mini-perfumes-25ml", "mini-perfumes-masculinos", "arabic-collection", "mini-perfumes-para-presente", "mini-perfumes-em-bh"]
  },
  {
    code: "A008",
    name: "Perfume Lattafa Fakhar Gold 25ml - Mini Perfume Compartilhável",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.9,
    gender: "Compartilhável",
    image: "/perfumes/A008 - Fakhar Gold.webp",
    description: "Uma rica mescla oriental ambarada com notas florais requintadas e acordes amadeirados resinosos de grande fixação.",
    notes: ["Notas Florais", "Especiarias", "Âmbar", "Madeiras Nobres", "Almíscar"],
    stock: 5,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia",
    slug: "lattafa-fakhar-gold-25ml",
    categorySlugs: ["mini-perfumes-importados", "mini-perfumes-25ml", "mini-perfumes-unissex", "arabic-collection", "mini-perfumes-para-presente", "mini-perfumes-em-bh"]
  },
  {
    code: "A009",
    name: "Perfume Lattafa Amethyst 25ml - Mini Perfume Compartilhável",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.9,
    gender: "Compartilhável",
    image: "/perfumes/A009- Amethyst.webp",
    description: "Mistura opulenta e misteriosa de rosas damascenas com a profundidade quente e terrosa do oud de luxo.",
    notes: ["Pimenta Rosa", "Rosa da Bulgária", "Rosa Turca", "Jasmim", "Oud", "Âmbar", "Baunilha"],
    stock: 6,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia",
    slug: "lattafa-amethyst-25ml",
    categorySlugs: ["mini-perfumes-importados", "mini-perfumes-25ml", "mini-perfumes-unissex", "arabic-collection", "mini-perfumes-para-presente", "mini-perfumes-em-bh"]
  },
  {
    code: "A010",
    name: "Perfume Lattafa Oud for Glory 25ml - Mini Perfume Compartilhável",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.9,
    gender: "Compartilhável",
    image: "/perfumes/A010- Oud for Glory.webp",
    description: "Fragrância amadeirada rica e nobre que gira em torno do precioso Agarwood, combinando lavanda e patchouli terroso.",
    notes: ["Açafrão", "Lavanda", "Noz-moscada", "Oud", "Patchouli", "Almíscar"],
    stock: 8,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia",
    slug: "lattafa-oud-for-glory-25ml",
    categorySlugs: ["mini-perfumes-importados", "mini-perfumes-25ml", "mini-perfumes-unissex", "arabic-collection", "mini-perfumes-para-presente", "mini-perfumes-em-bh"]
  },
  {
    code: "A011",
    name: "Perfume Lattafa Sublime 25ml - Mini Perfume Compartilhável",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.9,
    gender: "Compartilhável",
    image: "/perfumes/A011- Sublime.webp",
    description: "Aroma alegre, frutado e enérgico, perfeito para dias ensolarados de luxo.",
    notes: ["Maçã Vermelha", "Lichia", "Rosa", "Ameixa", "Jasmim", "Baunilha", "Musgo de Carvalho"],
    stock: 10,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia",
    slug: "lattafa-sublime-25ml",
    categorySlugs: ["mini-perfumes-importados", "mini-perfumes-25ml", "mini-perfumes-unissex", "arabic-collection", "mini-perfumes-para-presente", "mini-perfumes-em-bh"]
  },
  {
    code: "A012",
    name: "Perfume Lattafa Honor 25ml - Mini Perfume Masculino",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.9,
    gender: "Masculino",
    image: "/perfumes/A012- Honor.webp",
    description: "Visualização do poder árabe. Uma essência imponente combinando couro de alta costura e madeiras nobres.",
    notes: ["Especiarias", "Couro", "Madeira", "Âmbar"],
    stock: 4,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia",
    slug: "lattafa-honor-25ml",
    categorySlugs: ["mini-perfumes-importados", "mini-perfumes-25ml", "mini-perfumes-masculinos", "arabic-collection", "mini-perfumes-para-presente", "mini-perfumes-em-bh"]
  },
  {
    code: "A015",
    name: "Perfume Lattafa Emeer 25ml - Mini Perfume Compartilhável",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.9,
    gender: "Compartilhável",
    image: "/perfumes/A015- Emeer.webp",
    description: "Uma explosão cítrica brilhante e refrescante que evolui para um coração aromático e base amadeirada de cedro.",
    notes: ["Limão", "Bergamota", "Chá Verde", "Cardamomo", "Sândalo", "Cedro"],
    stock: 9,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia",
    slug: "lattafa-emeer-25ml",
    categorySlugs: ["mini-perfumes-importados", "mini-perfumes-25ml", "mini-perfumes-unissex", "arabic-collection", "mini-perfumes-para-presente", "mini-perfumes-em-bh"]
  },
  {
    code: "A016",
    name: "Perfume Lattafa Emaan 25ml - Mini Perfume Feminino",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.9,
    gender: "Feminino",
    image: "/perfumes/A016 - Emaan.webp",
    description: "Aroma floral verde fresco e delicado, exaltando sofisticação no dia a dia.",
    notes: ["Flor de Laranjeira", "Jasmim", "Calêndula", "Notas Verdes", "Patchouli"],
    stock: 6,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia",
    slug: "lattafa-emaan-25ml",
    categorySlugs: ["mini-perfumes-importados", "mini-perfumes-25ml", "mini-perfumes-femininos", "arabic-collection", "mini-perfumes-para-presente", "mini-perfumes-em-bh"]
  },
  {
    code: "A018",
    name: "Perfume Lattafa Musamam White 25ml - Mini Perfume Compartilhável",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.9,
    gender: "Compartilhável",
    image: "/perfumes/A018- Musamam White.webp",
    description: "Fragrância exótica ultra cremosa com coco, almíscar branco puro e notas solares aquecidas de sândalo.",
    notes: ["Coco", "Almíscar Branco", "Sândalo", "Notas Solares"],
    stock: 5,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia",
    slug: "lattafa-musamam-white-25ml",
    categorySlugs: ["mini-perfumes-importados", "mini-perfumes-25ml", "mini-perfumes-unissex", "arabic-collection", "mini-perfumes-para-presente", "mini-perfumes-em-bh"]
  },
  {
    code: "A020",
    name: "Perfume Lattafa Spectre Ghost 25ml - Mini Perfume Masculino",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.9,
    gender: "Masculino",
    image: "/perfumes/A020 - Spectre Ghost.webp",
    description: "Um aroma misterioso e potente com patchouli escuro, baunilha esfumaçada e madeiras nobres.",
    notes: ["Patchouli", "Baunilha", "Âmbar", "Madeiras Esfumaçadas"],
    stock: 8,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia",
    slug: "lattafa-spectre-ghost-25ml",
    categorySlugs: ["mini-perfumes-importados", "mini-perfumes-25ml", "mini-perfumes-masculinos", "arabic-collection", "mini-perfumes-para-presente", "mini-perfumes-em-bh"]
  },
  {
    code: "A024",
    name: "Perfume Lattafa Amber Royal 25ml - Mini Perfume Compartilhável",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.9,
    gender: "Compartilhável",
    image: "/perfumes/A024 - Amber Royal.webp",
    description: "O calor resinoso do âmbar real combinado com a doçura da baunilha de Madagascar.",
    notes: ["Âmbar", "Baunilha", "Sândalo", "Especiarias"],
    stock: 12,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia",
    slug: "lattafa-amber-royal-25ml",
    categorySlugs: ["mini-perfumes-importados", "mini-perfumes-25ml", "mini-perfumes-unissex", "arabic-collection", "mini-perfumes-para-presente", "mini-perfumes-em-bh"]
  },
  {
    code: "A026",
    name: "Perfume Lattafa Amber Rouge 25ml - Mini Perfume Compartilhável",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.9,
    gender: "Compartilhável",
    image: "/perfumes/A026- Amber Rouge.webp",
    description: "Inspirado no calor do açafrão, cedro e resina de abeto, criando uma assinatura olfativa inesquecível.",
    notes: ["Açafrão", "Jasmim", "Cedro", "Resina de Abeto"],
    stock: 10,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia",
    slug: "lattafa-amber-rouge-25ml",
    categorySlugs: ["mini-perfumes-importados", "mini-perfumes-25ml", "mini-perfumes-unissex", "arabic-collection", "mini-perfumes-para-presente", "mini-perfumes-em-bh"]
  },
  {
    code: "A028",
    name: "Perfume Armaf Club de Nuit Intense 25ml - Mini Perfume Masculino",
    brand: "Armaf",
    volume: "25ml",
    price: 79.9,
    gender: "Masculino",
    image: "/perfumes/A028 - Club de Nuit Intense.webp",
    description: "Uma abertura cítrica de limão siciliano que evolui para um coração floral nobre de jasmim e base de patchouli terroso.",
    notes: ["Limão", "Abacaxi", "Groselha Preta", "Bétula", "Jasmim", "Rosa", "Almíscar", "Patchouli"],
    stock: 18,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia",
    slug: "armaf-club-de-nuit-intense-25ml",
    categorySlugs: ["mini-perfumes-importados", "mini-perfumes-25ml", "mini-perfumes-masculinos", "brand-collection", "mini-perfumes-para-presente", "mini-perfumes-em-bh"]
  },
  {
    code: "A029",
    name: "Perfume Afnan 9PM 25ml - Mini Perfume Masculino",
    brand: "Afnan",
    volume: "25ml",
    price: 79.9,
    gender: "Masculino",
    image: "/perfumes/A029 - 9PM.webp",
    description: "Perfeito para noites marcantes. Possui uma saída doce de maçã vermelha, canela e baunilha sedutora.",
    notes: ["Maçã", "Canela", "Lavanda", "Flor de Laranjeira", "Baunilha", "Tonka", "Âmbar"],
    stock: 15,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia",
    slug: "afnan-9pm-25ml",
    categorySlugs: ["mini-perfumes-importados", "mini-perfumes-25ml", "mini-perfumes-masculinos", "brand-collection", "mini-perfumes-para-presente", "mini-perfumes-em-bh"]
  },
  {
    code: "A032",
    name: "Perfume Lattafa Nebras 25ml - Mini Perfume Feminino",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.9,
    gender: "Feminino",
    image: "/perfumes/A032- Nebras.webp",
    description: "Um aroma doce e reconfortante composto por cacau cremoso, baunilha morna e frutas vermelhas frescas.",
    notes: ["Cacau", "Baunilha", "Frutas Vermelhas", "Rosa", "Âmbar"],
    stock: 9,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia",
    slug: "lattafa-nebras-25ml",
    categorySlugs: ["mini-perfumes-importados", "mini-perfumes-25ml", "mini-perfumes-femininos", "arabic-collection", "mini-perfumes-para-presente", "mini-perfumes-em-bh"]
  },
  {
    code: "A033",
    name: "Perfume Lattafa Yara Candy 25ml - Mini Perfume Feminino",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.9,
    gender: "Feminino",
    image: "/perfumes/A033- Yara Candy.webp",
    description: "Uma explosão doce que remete a balas de frutas vermelhas caramelizadas. Extremamente jovem e magnético.",
    notes: ["Morango", "Groselha", "Caramelo", "Almíscar Doce"],
    stock: 13,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia",
    slug: "lattafa-yara-candy-25ml",
    categorySlugs: ["mini-perfumes-importados", "mini-perfumes-25ml", "mini-perfumes-femininos", "arabic-collection", "mini-perfumes-para-presente", "mini-perfumes-em-bh"]
  },
  {
    code: "A037",
    name: "Perfume Lattafa Sakeena 25ml - Mini Perfume Feminino",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.9,
    gender: "Feminino",
    image: "/perfumes/A037 – Sakeena.webp",
    description: "Fragrância marcante e frutada com notas de maracujá, framboesa doce e um toque elegante de café morno e patchouli.",
    notes: ["Maracujá", "Framboesa", "Café", "Rosa", "Patchouli"],
    stock: 8,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia",
    slug: "lattafa-sakeena-25ml",
    categorySlugs: ["mini-perfumes-importados", "mini-perfumes-25ml", "mini-perfumes-femininos", "arabic-collection", "mini-perfumes-para-presente", "mini-perfumes-em-bh"]
  }
];
