import { brandPerfumes } from './brandPerfumesData.js';

const arabicPerfumes = [
  {
    code: "A001",
    name: "Perfume Lattafa Asad 25ml - Mini Perfume Masculino",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.9,
    gender: "Masculino",
    image: "/perfumes/A001 – Asad.webp",
    description: "Uma fragrância oriental e amadeirada, com notas ricas de especiarias quentes, baunilha suave e âmbar refinado. Ideal para homens imponentes e misteriosos.",
    longDescription: "O Lattafa Asad é uma fragrância marcante e envolvente que captura a essência do homem moderno e confiante. Com uma abertura picante e especiada, ele rapidamente evolui para um coração amadeirado profundo e uma base deliciosamente cremosa e ambarada. Perfeito para ocasiões especiais ou noites onde você deseja deixar um rastro de mistério e sofisticação. Uma das fragrâncias árabes mais procuradas no mundo por sua incrível semelhança com um dos maiores sucessos da perfumaria mundial.",
    olfactoryFamily: "Amadeirado Especiado",
    inspiredBy: "Dior Sauvage Elixir",
    projection: "Intensa (2h a 3h)",
    duration: "Longa duração (10h a 12h)",
    notes: ["Pimenta Preta", "Abacaxi", "Tabaco", "Café", "Patchouli", "Âmbar", "Baunilha"],
    topNotes: ["Pimenta Preta", "Abacaxi", "Tabaco"],
    heartNotes: ["Café", "Patchouli", "Íris"],
    baseNotes: ["Âmbar", "Baunilha", "Madeiras Secas"],
    stock: 12,
    googleCategory: "Vestuário e acessórios > Joias e relógios > Relógios",
    slug: "lattafa-asad-25ml",
    categorySlugs: ["mini-perfumes-importados", "mini-perfumes-25ml", "mini-perfumes-masculinos", "arabic-collection", "mini-perfumes-para-presente", "mini-perfumes-em-bh"]
  },
  {
    code: "A002",
    name: "Perfume Lattafa Yara 25ml - Mini Perfume Feminino",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.9,
    gender: "Feminino",
    image: "/perfumes/A002- Yara.webp",
    description: "Um aroma doce, gourmand e extremamente envolvente. Com notas cremosas de baunilha, tangerina fresca e acordes tropicais de heliotrópio.",
    longDescription: "Lattafa Yara é a personificação da feminilidade e da doçura. Como um algodão-doce sofisticado fundido com um milkshake de morango cremoso e toques florais delicados, esta fragrância é viciante desde a primeira borrifada. Ideal para mulheres românticas, jovens de espírito e que adoram fragrâncias gourmands que rendem elogios constantes. É o queridinho das redes sociais por ser uma verdadeira explosão rosa de doçura e alegria.",
    olfactoryFamily: "Gourmand Floral Frutado",
    inspiredBy: "Criação Original (Vibe de fragrâncias cremosas como Cry Baby / Burberry Her Elixir)",
    projection: "Moderada a Intensa (2h)",
    duration: "Alta (8h a 10h)",
    notes: ["Heliotrópio", "Tangerina", "Orquídea", "Notas Tropicais", "Baunilha", "Almíscar", "Sândalo"],
    topNotes: ["Tangerina", "Heliotrópio", "Orquídea"],
    heartNotes: ["Notas Tropicais", "Gourmand"],
    baseNotes: ["Baunilha", "Almíscar", "Sândalo"],
    stock: 8,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia",
    slug: "lattafa-yara-25ml",
    categorySlugs: ["mini-perfumes-importados", "mini-perfumes-25ml", "mini-perfumes-femininos", "arabic-collection", "mini-perfumes-para-presente", "mini-perfumes-em-bh"]
  },
  {
    code: "A003",
    name: "Perfume Lattafa Yara Tous Laranja 25ml - Mini Perfume Feminino",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.9,
    gender: "Feminino",
    image: "/perfumes/A003- Yara Tous Laranja.webp",
    description: "Explosão frutada e tropical irresistível. Traz uma combinação solar de manga suculenta, maracujá doce e leite de coco cremoso.",
    longDescription: "Sinta o frescor do verão em um frasco! O Yara Tous (Laranja) é uma viagem olfativa para um paraíso tropical. Abre com uma suculenta e realista manga, acompanhada de maracujá e coco. É como saborear um coquetel exótico em uma praia paradisíaca. O coração floral traz elegância, enquanto a base de baunilha garante que a doçura tropical dure o dia todo. Perfeito para o clima quente do Brasil.",
    olfactoryFamily: "Floral Frutado Tropical",
    inspiredBy: "Paco Rabanne Fame / Mango Skin",
    projection: "Moderada (1h a 2h)",
    duration: "Moderada a Longa (6h a 8h)",
    notes: ["Manga", "Maracujá", "Coco", "Heliotrópio", "Jasmim", "Flor de Laranjeira", "Baunilha", "Almíscar"],
    topNotes: ["Manga", "Maracujá", "Coco"],
    heartNotes: ["Heliotrópio", "Jasmim", "Flor de Laranjeira"],
    baseNotes: ["Baunilha", "Almíscar", "Madeira de Cashmere"],
    stock: 15,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia",
    slug: "lattafa-yara-tous-laranja-25ml",
    categorySlugs: ["mini-perfumes-importados", "mini-perfumes-25ml", "mini-perfumes-femininos", "arabic-collection", "mini-perfumes-para-presente", "mini-perfumes-em-bh"]
  },
  {
    code: "A004",
    name: "Perfume Lattafa Yara Moi Branco 25ml - Mini Perfume Feminino",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.9,
    gender: "Feminino",
    image: "/perfumes/A004- Yara Moi Branco.webp",
    description: "Fragrância exótica que une a doçura do pêssego caramelizado à sofisticação do jasmim e do patchouli terroso.",
    longDescription: "Yara Moi (Branco) é a versão mais sofisticada e 'madura' da linha Yara. Uma combinação luxuosa de pêssego caramelizado com jasmim radiante, envolto por um patchouli terroso e sensual que traz um aspecto chipre moderno à fragrância. É um perfume elegante, cremoso e envolvente, ideal para o dia a dia de trabalho ou eventos elegantes onde se busca uma presença marcante e requintada.",
    olfactoryFamily: "Chipre Frutado Gourmet",
    inspiredBy: "Perfect Intense Marc Jacobs / Vibe de Good Girl",
    projection: "Marcante (2h)",
    duration: "Longa duração (8h a 10h)",
    notes: ["Pêssego", "Jasmim", "Caramelo", "Âmbar", "Patchouli", "Sândalo"],
    topNotes: ["Pêssego", "Jasmim"],
    heartNotes: ["Caramelo", "Âmbar"],
    baseNotes: ["Patchouli", "Sândalo"],
    stock: 9,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia",
    slug: "lattafa-yara-moi-branco-25ml",
    categorySlugs: ["mini-perfumes-importados", "mini-perfumes-25ml", "mini-perfumes-femininos", "arabic-collection", "mini-perfumes-para-presente", "mini-perfumes-em-bh"]
  },
  {
    code: "A005",
    name: "Perfume Lattafa Khamrah 25ml - Mini Perfume Compartilhável",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.9,
    gender: "Compartilhável",
    image: "/perfumes/A005- Khamrah.webp",
    description: "Aroma luxuoso e quente com acordes licorosos de conhaque, tâmaras doces, canela e pralina cremosa. Altamente sofisticado.",
    longDescription: "Khamrah é um espetáculo da perfumaria árabe. Esta fragrância compartilhável é como um licor quente e aconchegante servido em uma noite fria. O blend de tâmaras suculentas, canela especiada, pralina cremosa e um toque de mirra resinoso criam um aroma profundamente sedutor, doce, rico e envolvente. É um perfume de elite, ideal para encontros românticos, saídas noturnas ou sempre que você quiser se sentir uma realeza.",
    olfactoryFamily: "Oriental Gourmand",
    inspiredBy: "Kilian Angels' Share",
    projection: "Intensa e Envolvente (3h+)",
    duration: "Eterna (+12h na pele)",
    notes: ["Canela", "Noz-moscada", "Tâmaras", "Pralina", "Tuberosa", "Baunilha", "Âmbar", "Mirra"],
    topNotes: ["Canela", "Noz-moscada", "Bergamota"],
    heartNotes: ["Tâmaras", "Pralina", "Tuberosa", "Mahonial"],
    baseNotes: ["Baunilha", "Fava Tonka", "Madeira de Âmbar", "Mirra", "Benjoim", "Madeira de Akigala"],
    stock: 14,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia",
    slug: "lattafa-khamrah-25ml",
    categorySlugs: ["mini-perfumes-importados", "mini-perfumes-25ml", "mini-perfumes-unissex", "arabic-collection", "mini-perfumes-para-presente", "mini-perfumes-em-bh"]
  },
  {
    code: "A006",
    name: "Perfume Lattafa Fakhar Rose 25ml - Mini Perfume Feminino",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.9,
    gender: "Feminino",
    image: "/perfumes/A006- Fakhar Rose.webp",
    description: "Um buquê floral branco elegante e fresco. Combina jasmim e lírio a um toque de mel e almíscar suave.",
    longDescription: "Fakhar Rose, o 'Rose Gold' da Lattafa, é a pura elegância feminina encapsulada. Um floral branco hipnotizante, radiante e limpo, que exala a aura de uma mulher sofisticada. A abertura luminosa com notas frutadas se rende a um coração espetacular de jasmim, tuberosa e peônia, que evolui para uma base aveludada de baunilha e sândalo. É a fragrância perfeita para a mulher que quer marcar presença com graça e leveza, sem ser excessivamente doce.",
    olfactoryFamily: "Floral Branco",
    inspiredBy: "Givenchy L'Interdit",
    projection: "Marcante e Elegante (2h a 3h)",
    duration: "Longa duração (8h a 10h)",
    notes: ["Lírio", "Romã", "Jasmim", "Flor de Laranjeira", "Rosa", "Mel", "Almíscar", "Sândalo"],
    topNotes: ["Frutas Leves", "Romã", "Lírio", "Aldeídos"],
    heartNotes: ["Tuberosa", "Jasmim", "Gardênia", "Ylang-Ylang", "Rosa", "Madressilva"],
    baseNotes: ["Baunilha", "Ambroxan", "Almíscar Branco", "Sândalo"],
    stock: 7,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia",
    slug: "lattafa-fakhar-rose-25ml",
    categorySlugs: ["mini-perfumes-importados", "mini-perfumes-25ml", "mini-perfumes-femininos", "arabic-collection", "mini-perfumes-para-presente", "mini-perfumes-em-bh"]
  },
  {
    code: "A007",
    name: "Perfume Lattafa Fakhar Black 25ml - Mini Perfume Masculino",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.9,
    gender: "Masculino",
    image: "/perfumes/A007 - Fakhar Black.webp",
    description: "Fragrância fougère moderna com maçã crocante, lavanda aromática e notas amadeiradas profundas de cedro e âmbar.",
    longDescription: "Fakhar Black é a definição de masculinidade versátil e contemporânea. Este fougère moderno começa com um frescor vibrante de maçã verde, bergamota e gengibre, abrindo espaço para um coração elegante de sálvia, lavanda aromática e bagas de zimbro. A base amadeirada sela o acordo, criando um rastro de virilidade fresca que é tão apropriado para uma reunião de negócios em um terno bem cortado quanto para um encontro romântico no fim de semana.",
    olfactoryFamily: "Aromático Fougère",
    inspiredBy: "YSL Y Eau de Parfum",
    projection: "Moderada a Forte (2h)",
    duration: "Alta (8h a 10h)",
    notes: ["Maçã", "Gengibre", "Lavanda", "Sálvia", "Junípero", "Tonka", "Âmbar", "Cedro"],
    topNotes: ["Maçã Verde", "Bergamota", "Gengibre"],
    heartNotes: ["Lavanda", "Sálvia", "Bagas de Zimbro", "Gerânio"],
    baseNotes: ["Fava Tonka", "Madeira de Âmbar", "Cedro", "Vetiver"],
    stock: 11,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia",
    slug: "lattafa-fakhar-black-25ml",
    categorySlugs: ["mini-perfumes-importados", "mini-perfumes-25ml", "mini-perfumes-masculinos", "arabic-collection", "mini-perfumes-para-presente", "mini-perfumes-em-bh"]
  },
  {
    code: "A008",
    name: "Perfume Lattafa Fakhar Gold 25ml - Mini Perfume Compartilhável",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.9,
    gender: "Compartilhável",
    image: "/perfumes/A008 - Fakhar Gold.webp",
    description: "Uma rica mescla oriental ambarada com notas florais requintadas e acordes amadeirados resinosos de grande fixação.",
    longDescription: "Fakhar Gold Extrait transcende o gênero com sua mistura inebriante e oriental luxuosa. Uma joia dourada que combina a riqueza das especiarias orientais com um coração de tuberosa inebriante e um fundo profundamente amadeirado, resinoso e ambarado. É um perfume quente, opulento e denso. Seu aroma carrega um toque salgado elegante misturado a flores cremosas e madeiras macias que cria uma aura de riqueza, ideal para pessoas confiantes e de gosto refinado.",
    olfactoryFamily: "Âmbar Floral Amadeirado",
    inspiredBy: "Paco Rabanne One Million Parfum",
    projection: "Forte (2h a 3h)",
    duration: "Longa duração (10h+)",
    notes: ["Notas Florais", "Especiarias", "Âmbar", "Madeiras Nobres", "Almíscar"],
    topNotes: ["Toranja", "Pimenta Rosa", "Cardamomo"],
    heartNotes: ["Tuberosa", "Notas Solares", "Artemísia"],
    baseNotes: ["Âmbar", "Cashmeran", "Ládano", "Couro"],
    stock: 5,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia",
    slug: "lattafa-fakhar-gold-25ml",
    categorySlugs: ["mini-perfumes-importados", "mini-perfumes-25ml", "mini-perfumes-unissex", "arabic-collection", "mini-perfumes-para-presente", "mini-perfumes-em-bh"]
  },
  {
    code: "A009",
    name: "Perfume Lattafa Amethyst 25ml - Mini Perfume Compartilhável",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.9,
    gender: "Compartilhável",
    image: "/perfumes/A009- Amethyst.webp",
    description: "Mistura opulenta e misteriosa de rosas damascenas com a profundidade quente e terrosa do oud de luxo.",
    longDescription: "Bade'e Al Oud Amethyst é uma obra-prima que celebra a harmonia eterna entre a rosa e o oud (madeira de ágar). Esta fragrância envolvente e escura abre com uma pitada picante de pimenta rosa, que logo se transforma em um redemoinho opulento de rosa turca e rosa búlgara absolutas. O fundo amadeirado, defumado e levemente abaunilhado sustenta a composição por horas, proporcionando uma experiência olfativa real, luxuosa e profundamente misteriosa.",
    olfactoryFamily: "Âmbar Floral Oriental",
    inspiredBy: "Initio Atomic Rose",
    projection: "Intensa e Enorme (3h+)",
    duration: "Eterna (+12h)",
    notes: ["Pimenta Rosa", "Rosa da Bulgária", "Rosa Turca", "Jasmim", "Oud", "Âmbar", "Baunilha"],
    topNotes: ["Pimenta Rosa", "Bergamota"],
    heartNotes: ["Rosa Turca", "Rosa Búlgara", "Jasmim"],
    baseNotes: ["Oud", "Baunilha", "Âmbar"],
    stock: 6,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia",
    slug: "lattafa-amethyst-25ml",
    categorySlugs: ["mini-perfumes-importados", "mini-perfumes-25ml", "mini-perfumes-unissex", "arabic-collection", "mini-perfumes-para-presente", "mini-perfumes-em-bh"]
  },
  {
    code: "A010",
    name: "Perfume Lattafa Oud for Glory 25ml - Mini Perfume Compartilhável",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.9,
    gender: "Compartilhável",
    image: "/perfumes/A010- Oud for Glory.webp",
    description: "Fragrância amadeirada rica e nobre que gira em torno do precioso Agarwood, combinando lavanda e patchouli terroso.",
    longDescription: "Oud for Glory (Bade'e Al Oud) é indiscutivelmente uma das fragrâncias de oud mais aclamadas mundialmente. Este perfume carrega o DNA da perfumaria de nicho com uma elegância inigualável. O aroma inicia com a vivacidade do açafrão, noz-moscada e lavanda suave, descendo para um abismo de oud terroso, fumaça sutil e um patchouli denso e macio. Destila puro poder, sucesso e autoridade. Ideal para personalidades marcantes que não têm medo de atrair a atenção do ambiente.",
    olfactoryFamily: "Amadeirado Especiado",
    inspiredBy: "Initio Oud for Greatness",
    projection: "Extrema e Preenchedora (3h+)",
    duration: "Eterna (+12h)",
    notes: ["Açafrão", "Lavanda", "Noz-moscada", "Oud", "Patchouli", "Almíscar"],
    topNotes: ["Açafrão", "Noz-moscada", "Lavanda"],
    heartNotes: ["Oud (Madeira de Ágar)", "Patchouli"],
    baseNotes: ["Oud", "Patchouli", "Almíscar"],
    stock: 8,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia",
    slug: "lattafa-oud-for-glory-25ml",
    categorySlugs: ["mini-perfumes-importados", "mini-perfumes-25ml", "mini-perfumes-unissex", "arabic-collection", "mini-perfumes-para-presente", "mini-perfumes-em-bh"]
  },
  {
    code: "A011",
    name: "Perfume Lattafa Sublime 25ml - Mini Perfume Compartilhável",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.9,
    gender: "Compartilhável",
    image: "/perfumes/A011- Sublime.webp",
    description: "Aroma alegre, frutado e enérgico, perfeito para dias ensolarados de luxo.",
    longDescription: "Bade'e Al Oud Sublime se afasta do perfil escuro de seus irmãos e abraça a luminosidade. Uma fragrância incrivelmente alegre, frutada e tropical, onde a suculência da lichia e da maçã vermelha se encontram com a rosa fresca e uma delicada base de musgo. É uma explosão de suco de frutas frescas no início, assentando maravilhosamente em uma base floral elegante e macia. É compartilhável, pendendo ligeiramente para o lado feminino da balança, sendo excelente para climas quentes.",
    olfactoryFamily: "Floral Frutado",
    inspiredBy: "Kayali Eden Juicy Apple",
    projection: "Moderada (2h)",
    duration: "Moderada a Longa (6h a 8h)",
    notes: ["Maçã Vermelha", "Lichia", "Rosa", "Ameixa", "Jasmim", "Baunilha", "Musgo de Carvalho"],
    topNotes: ["Maçã Vermelha", "Lichia", "Rosa"],
    heartNotes: ["Ameixa", "Jasmim"],
    baseNotes: ["Musgo de Carvalho", "Baunilha", "Patchouli"],
    stock: 10,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia",
    slug: "lattafa-sublime-25ml",
    categorySlugs: ["mini-perfumes-importados", "mini-perfumes-25ml", "mini-perfumes-unissex", "arabic-collection", "mini-perfumes-para-presente", "mini-perfumes-em-bh"]
  },
  {
    code: "A012",
    name: "Perfume Lattafa Honor 25ml - Mini Perfume Masculino",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.9,
    gender: "Masculino",
    image: "/perfumes/A012- Honor.webp",
    description: "Visualização do poder árabe. Uma essência imponente combinando couro de alta costura e madeiras nobres.",
    longDescription: "Bade'e Al Oud Honor & Glory (Oud Branco) representa a excelência e o luxo majestoso. Esta edição inova ao trazer um dulçor único de abacaxi maduro misturado ao toque gourmand do crème brûlée, antes de se assentar em uma sinfonia de açafrão, canela, especiarias quentes e uma base cremosa de sândalo. É uma assinatura elegante e festiva, doce mas complexa, irradiando confiança e prestígio a cada movimento.",
    olfactoryFamily: "Oriental Especiado Gourmand",
    inspiredBy: "Criação Original (com estilo de niche e Tribeca Bond No 9)",
    projection: "Forte (2h a 3h)",
    duration: "Longa (+10h)",
    notes: ["Abacaxi", "Crème Brûlée", "Canela", "Pimenta Preta", "Baunilha", "Sândalo", "Cashmeran"],
    topNotes: ["Abacaxi", "Crème Brûlée"],
    heartNotes: ["Canela", "Benjoim", "Pimenta Preta", "Cúrcuma"],
    baseNotes: ["Baunilha", "Sândalo", "Cashmeran", "Musgo"],
    stock: 4,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia",
    slug: "lattafa-honor-25ml",
    categorySlugs: ["mini-perfumes-importados", "mini-perfumes-25ml", "mini-perfumes-masculinos", "arabic-collection", "mini-perfumes-para-presente", "mini-perfumes-em-bh"]
  },
  {
    code: "A015",
    name: "Perfume Lattafa Emeer 25ml - Mini Perfume Compartilhável",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.9,
    gender: "Compartilhável",
    image: "/perfumes/A015- Emeer.webp",
    description: "Uma explosão cítrica brilhante e refrescante que evolui para um coração aromático e base amadeirada de cedro.",
    longDescription: "Lattafa Emeer é como os primeiros raios de sol em uma floresta fresca. A fragrância inicia com uma combinação revigorante e efervescente de limão siciliano, bergamota verde e folhas de sálvia. A medida que seca na pele, notas elegantes de chá branco e cardamomo se revelam, criando um ar puro e relaxante, que finaliza em um amadeirado suave e almiscarado. É a escolha definitiva para quem ama fragrâncias frescas, limpas, energizantes e elegantes para qualquer ocasião.",
    olfactoryFamily: "Cítrico Aromático Amadeirado",
    inspiredBy: "Clive Christian Town & Country",
    projection: "Moderada (1h a 2h)",
    duration: "Moderada a Longa (7h a 9h)",
    notes: ["Limão", "Bergamota", "Chá Verde", "Cardamomo", "Sândalo", "Cedro"],
    topNotes: ["Limão", "Bergamota", "Sálvia", "Zimbro"],
    heartNotes: ["Chá Branco", "Cardamomo", "Sândalo", "Olíbano"],
    baseNotes: ["Âmbar Cinzento", "Patchouli", "Madeira de Cedro", "Cashmeran"],
    stock: 9,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia",
    slug: "lattafa-emeer-25ml",
    categorySlugs: ["mini-perfumes-importados", "mini-perfumes-25ml", "mini-perfumes-unissex", "arabic-collection", "mini-perfumes-para-presente", "mini-perfumes-em-bh"]
  },
  {
    code: "A016",
    name: "Perfume Lattafa Emaan 25ml - Mini Perfume Feminino",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.9,
    gender: "Feminino",
    image: "/perfumes/A016 - Emaan.webp",
    description: "Aroma floral verde fresco e delicado, exaltando sofisticação no dia a dia.",
    longDescription: "Lattafa Emaan celebra a beleza natural e despretensiosa. Uma combinação luminosa de bergamota, groselha negra e flor de laranjeira compõem sua saída. O núcleo é dominado por um jasmim puro e cremoso entrelaçado à tuberosa sedutora, resultando numa aura intensamente feminina. O toque final de patchouli, baunilha suave e almíscar garante uma silagem charmosa e duradoura. Excelente assinatura olfativa diária para uma mulher elegante e imponente.",
    olfactoryFamily: "Chypre Floral",
    inspiredBy: "Giorgio Armani My Way Intense / Givenchy L'Interdit",
    projection: "Marcante (2h)",
    duration: "Longa duração (8h a 10h)",
    notes: ["Flor de Laranjeira", "Jasmim", "Calêndula", "Notas Verdes", "Patchouli"],
    topNotes: ["Groselha Negra", "Bergamota", "Flor de Laranjeira"],
    heartNotes: ["Jasmim", "Tuberosa", "Calêndula"],
    baseNotes: ["Patchouli", "Baunilha", "Almíscar Branco", "Madeira de Cedro"],
    stock: 6,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia",
    slug: "lattafa-emaan-25ml",
    categorySlugs: ["mini-perfumes-importados", "mini-perfumes-25ml", "mini-perfumes-femininos", "arabic-collection", "mini-perfumes-para-presente", "mini-perfumes-em-bh"]
  },
  {
    code: "A018",
    name: "Perfume Lattafa Musamam White 25ml - Mini Perfume Compartilhável",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.9,
    gender: "Compartilhável",
    image: "/perfumes/A018- Musamam White.webp",
    description: "Fragrância exótica ultra cremosa com coco, almíscar branco puro e notas solares aquecidas de sândalo.",
    longDescription: "Musamam White Intense é uma viagem olfativa calmante e opulenta. Sendo um dos lançamentos mais requintados, ele apresenta um coco suave, não muito doce, envolvido por um almíscar branco sedoso e macio como nuvens. Notas de ylang-ylang trazem uma vibe solar dourada, finalizando numa base cremosa de sândalo australiano. É um perfume confortável, íntimo, cheiro de pessoa rica e bem tratada, excelente para relaxar, para um passeio vespertino ou encontros em climas quentes.",
    olfactoryFamily: "Amadeirado Floral Almiscarado",
    inspiredBy: "Nishane Nefs / Bvlgari Le Gemme Tygar (interpretação clean)",
    projection: "Moderada (1.5h a 2h)",
    duration: "Longa (8h+)",
    notes: ["Coco", "Almíscar Branco", "Sândalo", "Notas Solares"],
    topNotes: ["Bergamota", "Laranja", "Especiarias Frescas"],
    heartNotes: ["Côco", "Ylang-Ylang", "Mahonial", "Ambroxan"],
    baseNotes: ["Sândalo", "Benjoim", "Almíscar Branco"],
    stock: 5,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia",
    slug: "lattafa-musamam-white-25ml",
    categorySlugs: ["mini-perfumes-importados", "mini-perfumes-25ml", "mini-perfumes-unissex", "arabic-collection", "mini-perfumes-para-presente", "mini-perfumes-em-bh"]
  },
  {
    code: "A020",
    name: "Perfume Lattafa Spectre Ghost 25ml - Mini Perfume Masculino",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.9,
    gender: "Masculino",
    image: "/perfumes/A020 - Spectre Ghost.webp",
    description: "Um aroma misterioso e potente com patchouli escuro, baunilha esfumaçada e madeiras nobres.",
    longDescription: "Spectre Ghost (da linha Fragrance World/Lattafa) é uma composição enigmática e magnética. Com um DNA que transpira nobreza e mistério, ele equilibra o ardor frio do cardamomo com a riqueza doce e defumada da baunilha negra. Uma base de café torrado e patchouli sombrio confere profundidade inexplorada, rendendo a esta fragrância o título de 'matador noturno'. Homens que vestem Ghost não passam despercebidos. Exclusivo para noites, baladas ou encontros íntimos.",
    olfactoryFamily: "Oriental Especiado Amadeirado",
    inspiredBy: "Nishane Ani / YSL Tuxedo",
    projection: "Intensa (3h)",
    duration: "Eterna (10h a 12h)",
    notes: ["Patchouli", "Baunilha", "Âmbar", "Madeiras Esfumaçadas"],
    topNotes: ["Gengibre", "Cardamomo", "Pimenta Rosa"],
    heartNotes: ["Rosa Turca", "Groselha Preta", "Baunilha Defumada"],
    baseNotes: ["Patchouli", "Cedro", "Sândalo", "Café"],
    stock: 8,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia",
    slug: "lattafa-spectre-ghost-25ml",
    categorySlugs: ["mini-perfumes-importados", "mini-perfumes-25ml", "mini-perfumes-masculinos", "arabic-collection", "mini-perfumes-para-presente", "mini-perfumes-em-bh"]
  },
  {
    code: "A024",
    name: "Perfume Lattafa Amber Royal 25ml - Mini Perfume Compartilhável",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.9,
    gender: "Compartilhável",
    image: "/perfumes/A024 - Amber Royal.webp",
    description: "O calor resinoso do âmbar real combinado com a doçura da baunilha de Madagascar.",
    longDescription: "Amber Royal é o calor dourado em formato de perfume. Uma viagem real ao coração do oriente médio, construída sobre as resinas mais nobres e caras da perfumaria. O calor ambarado domina do começo ao fim, temperado de forma magnífica com canela em pau, fava tonka e baunilha sedutora. Um leve fundo almiscarado e de couro garante uma fixação extraordinária. Rico, viscoso e quente, o Amber Royal é a escolha suprema para dias frios de outono e inverno.",
    olfactoryFamily: "Âmbar Especiado",
    inspiredBy: "Grand Soir Maison Francis Kurkdjian",
    projection: "Marcante e Quente (2h a 3h)",
    duration: "Longa duração (10h+)",
    notes: ["Âmbar", "Baunilha", "Sândalo", "Especiarias"],
    topNotes: ["Canela", "Noz-moscada"],
    heartNotes: ["Ládano Espanhol", "Fava Tonka"],
    baseNotes: ["Âmbar", "Baunilha de Madagascar", "Almíscar"],
    stock: 12,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia",
    slug: "lattafa-amber-royal-25ml",
    categorySlugs: ["mini-perfumes-importados", "mini-perfumes-25ml", "mini-perfumes-unissex", "arabic-collection", "mini-perfumes-para-presente", "mini-perfumes-em-bh"]
  },
  {
    code: "A026",
    name: "Perfume Lattafa Amber Rouge 25ml - Mini Perfume Compartilhável",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.9,
    gender: "Compartilhável",
    image: "/perfumes/A026- Amber Rouge.webp",
    description: "Inspirado no calor do açafrão, cedro e resina de abeto, criando uma assinatura olfativa inesquecível.",
    longDescription: "Orientica Amber Rouge (da mesma casa de luxo árabe Al Haramain) é a pura expressão do luxo magnético e transparente. Famoso mundialmente pelo seu acorde doce, salgado, amadeirado e arejado, este perfume apresenta um açafrão precioso ao lado de amêndoas amargas e a doçura translúcida do jasmim egípcio. No fundo, a madeira de cedro e a resina de abeto se unem com o ambroxan, projetando um rastro viciante e etéreo que as pessoas conseguem sentir a metros de distância. Extremamente elegante, não pesa, mas se faz notar em qualquer ambiente.",
    olfactoryFamily: "Âmbar Floral Amadeirado",
    inspiredBy: "Maison Francis Kurkdjian Baccarat Rouge 540 Extrait",
    projection: "Marcante e Etérea (Rastro de 3h+)",
    duration: "Eterna (+12h)",
    notes: ["Açafrão", "Jasmim", "Cedro", "Resina de Abeto"],
    topNotes: ["Açafrão", "Amêndoa Amarga", "Jasmim Egípcio"],
    heartNotes: ["Cedro", "Madeira de Âmbar"],
    baseNotes: ["Resina de Abeto", "Ambroxan", "Almíscar"],
    stock: 10,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia",
    slug: "lattafa-amber-rouge-25ml",
    categorySlugs: ["mini-perfumes-importados", "mini-perfumes-25ml", "mini-perfumes-unissex", "arabic-collection", "mini-perfumes-para-presente", "mini-perfumes-em-bh"]
  },
  {
    code: "A028",
    name: "Perfume Armaf Club de Nuit Intense 25ml - Mini Perfume Masculino",
    brand: "Armaf",
    volume: "25ml",
    price: 79.9,
    gender: "Masculino",
    image: "/perfumes/A028 - Club de Nuit Intense.webp",
    description: "Uma abertura cítrica de limão siciliano que evolui para um coração floral nobre de jasmim e base de patchouli terroso.",
    longDescription: "O REI da perfumaria árabe. O Armaf Club de Nuit Intense Man é um fenômeno de vendas mundial, reconhecido por sua projeção e longevidade absurdamente potentes e aroma magnético de homem poderoso, rico e bem sucedido. Inicia com um soco cítrico de limão siciliano, abacaxi maduro e maçã, para logo suavizar em um coração incensado com bétula defumada, rosa negra e patchouli. É um aroma inconfundível, extremamente masculino, fresco mas com uma base esfumaçada que atrai inúmeros elogios. Excelente como assinatura para o ano todo.",
    olfactoryFamily: "Amadeirado Especiado Frutado",
    inspiredBy: "Creed Aventus",
    projection: "Extrema (Preenche o ambiente por 3h)",
    duration: "Eterna (+12h)",
    notes: ["Limão", "Abacaxi", "Groselha Preta", "Bétula", "Jasmim", "Rosa", "Almíscar", "Patchouli"],
    topNotes: ["Limão Siciliano", "Abacaxi", "Groselha Preta", "Maçã", "Bergamota"],
    heartNotes: ["Bétula", "Jasmim", "Rosa"],
    baseNotes: ["Almíscar", "Âmbar Cinzento", "Patchouli", "Baunilha"],
    stock: 18,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia",
    slug: "armaf-club-de-nuit-intense-25ml",
    categorySlugs: ["mini-perfumes-importados", "mini-perfumes-25ml", "mini-perfumes-masculinos", "brand-collection", "mini-perfumes-para-presente", "mini-perfumes-em-bh"]
  },
  {
    code: "A029",
    name: "Perfume Afnan 9PM 25ml - Mini Perfume Masculino",
    brand: "Afnan",
    volume: "25ml",
    price: 79.9,
    gender: "Masculino",
    image: "/perfumes/A029 - 9PM.webp",
    description: "Perfeito para noites marcantes. Possui uma saída doce de maçã vermelha, canela e baunilha sedutora.",
    longDescription: "Como o nome indica, o Afnan 9PM foi criado para as noites e as badalações. O 'rei das baladas' na perfumaria árabe, é um suco envolvente, adocicado e incrivelmente magnético. Ele abre com a suculência da maçã silvestre acompanhada de canela, criando um aspecto frutado quente. O coração ganha uma nuance fresca e elegante de lavanda com flor de laranjeira, mas a mágica ocorre no fundo: uma base arrebatadora e inebriante de fava tonka, baunilha negra e patchouli que gruda na pele e atrai os olhares e elogios.",
    olfactoryFamily: "Oriental Baunilha Aromático",
    inspiredBy: "Jean Paul Gaultier Ultra Male",
    projection: "Forte a Intensa (Bombástico nas primeiras 3h)",
    duration: "Longa duração (10h a 12h)",
    notes: ["Maçã", "Canela", "Lavanda", "Flor de Laranjeira", "Baunilha", "Tonka", "Âmbar"],
    topNotes: ["Maçã", "Canela", "Lavanda Silvestre", "Bergamota"],
    heartNotes: ["Flor de Laranjeira", "Lírio-do-vale"],
    baseNotes: ["Baunilha", "Fava Tonka", "Âmbar", "Patchouli"],
    stock: 15,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia",
    slug: "afnan-9pm-25ml",
    categorySlugs: ["mini-perfumes-importados", "mini-perfumes-25ml", "mini-perfumes-masculinos", "brand-collection", "mini-perfumes-para-presente", "mini-perfumes-em-bh"]
  },
  {
    code: "A032",
    name: "Perfume Lattafa Nebras 25ml - Mini Perfume Feminino",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.9,
    gender: "Feminino",
    image: "/perfumes/A032- Nebras.webp",
    description: "Um aroma doce e reconfortante composto por cacau cremoso, baunilha morna e frutas vermelhas frescas.",
    longDescription: "Lattafa Nebras é o conforto e a sensualidade engarrafados. Uma fragrância incrivelmente sofisticada para as amantes do gênero gourmand, que evoca a sensação de saborear morangos silvestres cobertos com um chocolate ao leite muito quente e baunilha cremosa de alta qualidade. Não é excessivamente doce e enjoativo, a fava tonka com as notas levemente florais e ambaradas equilibram a composição, proporcionando um aroma cremoso, aveludado e acolhedor perfeito para encontros, dias frios ou usar como assinatura para se sentir deliciosa.",
    olfactoryFamily: "Gourmand Oriental",
    inspiredBy: "Billie Eilish Eilish",
    projection: "Moderada a Forte (2h)",
    duration: "Alta (8h a 10h)",
    notes: ["Cacau", "Baunilha", "Frutas Vermelhas", "Rosa", "Âmbar"],
    topNotes: ["Frutas Vermelhas", "Mandarina"],
    heartNotes: ["Cacau", "Baunilha", "Rosa"],
    baseNotes: ["Fava Tonka", "Âmbar", "Almíscar"],
    stock: 9,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia",
    slug: "lattafa-nebras-25ml",
    categorySlugs: ["mini-perfumes-importados", "mini-perfumes-25ml", "mini-perfumes-femininos", "arabic-collection", "mini-perfumes-para-presente", "mini-perfumes-em-bh"]
  },
  {
    code: "A033",
    name: "Perfume Lattafa Yara Candy 25ml - Mini Perfume Feminino",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.9,
    gender: "Feminino",
    image: "/perfumes/A033- Yara Candy.webp",
    description: "Uma explosão doce que remete a balas de frutas vermelhas caramelizadas. Extremamente jovem e magnético.",
    longDescription: "A versão mais recente, vibrante e jovial da linha Yara. O Yara Candy traz uma abordagem alegre, efervescente e irresistível. O cheiro remete imediatamente a balas de morango azedinhas, doces de festa e xarope de frutas vermelhas suculentas, fundindo-se de maneira deliciosa na pele com notas macias de almíscar e um fundo suave de baunilha caramelizada. É o perfume das 'IT Girls', extremamente alegre, descontraído e projetado para atrair elogios pelo seu cheiro 'delicioso' e divertido.",
    olfactoryFamily: "Gourmand Frutado Doce",
    inspiredBy: "Lancôme La Nuit Trésor Nude / Cacharel Yes I Am (Vibe doce)",
    projection: "Marcante e Lúdica (2h)",
    duration: "Moderada a Longa (7h a 8h)",
    notes: ["Morango", "Groselha", "Caramelo", "Almíscar Doce"],
    topNotes: ["Morango Glaceado", "Framboesa", "Groselha Vermelha"],
    heartNotes: ["Rosa Delicada", "Jasmim Estrela", "Balas de Goma"],
    baseNotes: ["Caramelo", "Baunilha", "Almíscar Branco"],
    stock: 13,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia",
    slug: "lattafa-yara-candy-25ml",
    categorySlugs: ["mini-perfumes-importados", "mini-perfumes-25ml", "mini-perfumes-femininos", "arabic-collection", "mini-perfumes-para-presente", "mini-perfumes-em-bh"]
  },
  {
    code: "A037",
    name: "Perfume Lattafa Sakeena 25ml - Mini Perfume Feminino",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.9,
    gender: "Feminino",
    image: "/perfumes/A037 – Sakeena.webp",
    description: "Fragrância marcante e frutada com notas de maracujá, framboesa doce e um toque elegante de café morno e patchouli.",
    longDescription: "Lattafa Sakeena é uma jornada olfativa ousada e profundamente feminina. O início surpreende com frutas tropicais incrivelmente suculentas e picantes – notadamente um maracujá doce e vivo combinado com framboesa. Mas é no coração da fragrância que a mágica acontece: um buquê de rosas vermelhas acompanhado pelo calor inesperado de grãos de café torrados. A base amadeirada, musgosa e ambarada entrega uma performance excelente e madura. Sakeena é perfeito para a mulher autoconfiante, empoderada e que não tem medo de usar uma fragrância que seja ao mesmo tempo frutada e escandalosamente sofisticada.",
    olfactoryFamily: "Floral Frutado Amadeirado",
    inspiredBy: "Tiziana Terenzi Kirke / Sospiro Erba Pura (Com toque de Café)",
    projection: "Forte (Projeta longe nas primeiras 2h)",
    duration: "Longa duração (10h+)",
    notes: ["Maracujá", "Framboesa", "Café", "Rosa", "Patchouli"],
    topNotes: ["Maracujá", "Framboesa", "Tangerina", "Acordos Ozônicos"],
    heartNotes: ["Flor de Laranjeira", "Rosa", "Café Torrado", "Sal Marinho"],
    baseNotes: ["Pralina", "Baunilha", "Patchouli", "Almíscar"],
    stock: 8,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia",
    slug: "lattafa-sakeena-25ml",
    categorySlugs: ["mini-perfumes-importados", "mini-perfumes-25ml", "mini-perfumes-femininos", "arabic-collection", "mini-perfumes-para-presente", "mini-perfumes-em-bh"]
  }
];

export const perfumes = [...arabicPerfumes, ...brandPerfumes];
