export const perfumes = [
  {
    code: "A001",
    name: "Lattafa Asad",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.90,
    gender: "Masculino",
    image: "/perfumes/A001 – Asad.webp",
    description: "Uma fragrância oriental e amadeirada, com notas ricas de especiarias quentes, baunilha suave e âmbar refinado. Ideal para homens imponentes e misteriosos.",
    notes: ["Pimenta Preta", "Abacaxi", "Tabaco", "Café", "Patchouli", "Âmbar", "Baunilha"],
    stock: 12,
    googleCategory: "Vestuário e acessórios > Joias e relógios > Relógios" // Categoria Google Shopping aproximada para perfumes importados de luxo
  },
  {
    code: "A002",
    name: "Lattafa Yara",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.90,
    gender: "Feminino",
    image: "/perfumes/A002- Yara.webp",
    description: "Um aroma doce, gourmand e extremamente envolvente. Com notas cremosas de baunilha, tangerina fresca e acordes tropicais de heliotrópio.",
    notes: ["Heliotrópio", "Tangerina", "Orquídea", "Notas Tropicais", "Baunilha", "Almíscar", "Sândalo"],
    stock: 8,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia"
  },
  {
    code: "A003",
    name: "Lattafa Yara Tous Laranja",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.90,
    gender: "Feminino",
    image: "/perfumes/A003- Yara Tous Laranja.webp",
    description: "Explosão frutada e tropical irresistível. Traz uma combinação solar de manga suculenta, maracujá doce e leite de coco cremoso.",
    notes: ["Manga", "Maracujá", "Coco", "Heliotrópio", "Jasmim", "Flor de Laranjeira", "Baunilha", "Almíscar"],
    stock: 15,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia"
  },
  {
    code: "A004",
    name: "Lattafa Yara Moi Branco",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.90,
    gender: "Feminino",
    image: "/perfumes/A004- Yara Moi Branco.webp",
    description: "Fragrância exótica que une a doçura do pêssego caramelizado à sofisticação do jasmim e do patchouli terroso.",
    notes: ["Pêssego", "Jasmim", "Caramelo", "Âmbar", "Patchouli", "Sândalo"],
    stock: 9,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia"
  },
  {
    code: "A005",
    name: "Lattafa Khamrah",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.90,
    gender: "Compartilhável",
    image: "/perfumes/A005- Khamrah.webp",
    description: "Aroma luxuoso e quente com acordes licorosos de conhaque, tâmaras doces, canela e pralina cremosa. Altamente sofisticado.",
    notes: ["Canela", "Noz-moscada", "Tâmaras", "Pralina", "Tuberosa", "Baunilha", "Âmbar", "Mirra"],
    stock: 14,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia"
  },
  {
    code: "A006",
    name: "Lattafa Fakhar Rose",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.90,
    gender: "Feminino",
    image: "/perfumes/A006- Fakhar Rose.webp",
    description: "Um buquê floral branco elegante e fresco. Combina jasmim e lírio a um toque de mel e almíscar suave.",
    notes: ["Lírio", "Romã", "Jasmim", "Flor de Laranjeira", "Rosa", "Mel", "Almíscar", "Sândalo"],
    stock: 7,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia"
  },
  {
    code: "A007",
    name: "Lattafa Fakhar Black",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.90,
    gender: "Masculino",
    image: "/perfumes/A007 - Fakhar Black.webp",
    description: "Fragrância fougère moderna com maçã crocante, lavanda aromática e notas amadeiradas profundas de cedro e âmbar.",
    notes: ["Maçã", "Gengibre", "Lavanda", "Sálvia", "Junípero", "Tonka", "Âmbar", "Cedro"],
    stock: 11,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia"
  },
  {
    code: "A008",
    name: "Lattafa Fakhar Gold",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.90,
    gender: "Compartilhável",
    image: "/perfumes/A008 - Fakhar Gold.webp",
    description: "Uma rica mescla oriental ambarada com notas florais requintadas e acordes amadeirados resinosos de grande fixação.",
    notes: ["Notas Florais", "Especiarias", "Âmbar", "Madeiras Nobres", "Almíscar"],
    stock: 5,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia"
  },
  {
    code: "A009",
    name: "Lattafa Amethyst",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.90,
    gender: "Compartilhável",
    image: "/perfumes/A009- Amethyst.webp",
    description: "Mistura opulenta e misteriosa de rosas damascenas com a profundidade quente e terrosa do oud de luxo.",
    notes: ["Pimenta Rosa", "Rosa da Bulgária", "Rosa Turca", "Jasmim", "Oud", "Âmbar", "Baunilha"],
    stock: 6,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia"
  },
  {
    code: "A010",
    name: "Lattafa Oud for Glory",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.90,
    gender: "Compartilhável",
    image: "/perfumes/A010- Oud for Glory.webp",
    description: "Fragrância amadeirada rica e nobre que gira em torno do precioso Agarwood, combinando lavanda e patchouli terroso.",
    notes: ["Açafrão", "Lavanda", "Noz-moscada", "Oud", "Patchouli", "Almíscar"],
    stock: 8,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia"
  },
  {
    code: "A011",
    name: "Lattafa Sublime",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.90,
    gender: "Compartilhável",
    image: "/perfumes/A011- Sublime.webp",
    description: "Aroma alegre, frutado e enérgico, perfeito para dias ensolarados de luxo.",
    notes: ["Maçã Vermelha", "Lichia", "Rosa", "Ameixa", "Jasmim", "Baunilha", "Musgo de Carvalho"],
    stock: 10,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia"
  },
  {
    code: "A012",
    name: "Lattafa Honor",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.90,
    gender: "Masculino",
    image: "/perfumes/A012- Honor.webp",
    description: "Visualização do poder árabe. Uma essência imponente combinando couro de alta costura e madeiras nobres.",
    notes: ["Especiarias", "Couro", "Madeira", "Âmbar"],
    stock: 4,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia"
  },
  {
    code: "A015",
    name: "Lattafa Emeer",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.90,
    gender: "Compartilhável",
    image: "/perfumes/A015- Emeer.webp",
    description: "Uma explosão cítrica brilhante e refrescante que evolui para um coração aromático e base amadeirada de cedro.",
    notes: ["Limão", "Bergamota", "Chá Verde", "Cardamomo", "Sândalo", "Cedro"],
    stock: 9,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia"
  },
  {
    code: "A016",
    name: "Lattafa Emaan",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.90,
    gender: "Feminino",
    image: "/perfumes/A016 - Emaan.webp",
    description: "Aroma floral verde fresco e delicado, exaltando sofisticação no dia a dia.",
    notes: ["Flor de Laranjeira", "Jasmim", "Calêndula", "Notas Verdes", "Patchouli"],
    stock: 6,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia"
  },
  {
    code: "A018",
    name: "Lattafa Musamam White",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.90,
    gender: "Compartilhável",
    image: "/perfumes/A018- Musamam White.webp",
    description: "Fragrância exótica ultra cremosa com coco, almíscar branco puro e notas solares aquecidas de sândalo.",
    notes: ["Coco", "Almíscar Branco", "Sândalo", "Notas Solares"],
    stock: 5,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia"
  },
  {
    code: "A020",
    name: "Lattafa Spectre Ghost",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.90,
    gender: "Masculino",
    image: "/perfumes/A020 - Spectre Ghost.webp",
    description: "Um aroma misterioso e potente com patchouli escuro, baunilha esfumaçada e madeiras nobres.",
    notes: ["Patchouli", "Baunilha", "Âmbar", "Madeiras Esfumaçadas"],
    stock: 8,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia"
  },
  {
    code: "A024",
    name: "Lattafa Amber Royal",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.90,
    gender: "Compartilhável",
    image: "/perfumes/A024 - Amber Royal.webp",
    description: "O calor resinoso do âmbar real combinado com a doçura da baunilha de Madagascar.",
    notes: ["Âmbar", "Baunilha", "Sândalo", "Especiarias"],
    stock: 12,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia"
  },
  {
    code: "A026",
    name: "Lattafa Amber Rouge",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.90,
    gender: "Compartilhável",
    image: "/perfumes/A026- Amber Rouge.webp",
    description: "Inspirado no calor do açafrão, cedro e resina de abeto, criando uma assinatura olfativa inesquecível.",
    notes: ["Açafrão", "Jasmim", "Cedro", "Resina de Abeto"],
    stock: 10,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia"
  },
  {
    code: "A028",
    name: "Armaf Club de Nuit Intense",
    brand: "Armaf",
    volume: "25ml",
    price: 79.90,
    gender: "Masculino",
    image: "/perfumes/A028 - Club de Nuit Intense.webp",
    description: "Uma abertura cítrica de limão siciliano que evolui para um coração floral nobre de jasmim e base de patchouli terroso.",
    notes: ["Limão", "Abacaxi", "Groselha Preta", "Bétula", "Jasmim", "Rosa", "Almíscar", "Patchouli"],
    stock: 18,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia"
  },
  {
    code: "A029",
    name: "Afnan 9PM",
    brand: "Afnan",
    volume: "25ml",
    price: 79.90,
    gender: "Masculino",
    image: "/perfumes/A029 - 9PM.webp",
    description: "Perfeito para noites marcantes. Possui uma saída doce de maçã vermelha, canela e baunilha sedutora.",
    notes: ["Maçã", "Canela", "Lavanda", "Flor de Laranjeira", "Baunilha", "Tonka", "Âmbar"],
    stock: 15,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia"
  },
  {
    code: "A032",
    name: "Lattafa Nebras",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.90,
    gender: "Feminino",
    image: "/perfumes/A032- Nebras.webp",
    description: "Um aroma doce e reconfortante composto por cacau cremoso, baunilha morna e frutas vermelhas frescas.",
    notes: ["Cacau", "Baunilha", "Frutas Vermelhas", "Rosa", "Âmbar"],
    stock: 9,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia"
  },
  {
    code: "A033",
    name: "Lattafa Yara Candy",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.90,
    gender: "Feminino",
    image: "/perfumes/A033- Yara Candy.webp",
    description: "Uma explosão doce que remete a balas de frutas vermelhas caramelizadas. Extremamente jovem e magnético.",
    notes: ["Morango", "Groselha", "Caramelo", "Almíscar Doce"],
    stock: 13,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia"
  },
  {
    code: "A037",
    name: "Lattafa Sakeena",
    brand: "Lattafa Perfumes",
    volume: "25ml",
    price: 79.90,
    gender: "Feminino",
    image: "/perfumes/A037 – Sakeena.webp",
    description: "Fragrância marcante e frutada com notas de maracujá, framboesa doce e um toque elegante de café morno e patchouli.",
    notes: ["Maracujá", "Framboesa", "Café", "Rosa", "Patchouli"],
    stock: 8,
    googleCategory: "Saúde e beleza > Cuidados pessoais > Cosméticos > Perfume e colônia"
  }
];
